### ISSUE TITLE
Undefined method causing dev/build failures

### ISSUE THREAD

**Issue by indygriffiths** [silverstripe/silverstripe-dynamodb#37]
Spotted a failed deployment this morning for a stack on PHP 7.2.
```
[2019-07-04 06:36:30] OUT >   - Installing silverstripe/framework (4.4.1): Loading from cache
[2019-07-04 06:36:31] OUT >   - Installing silverstripe/dynamodb (4.0.2): Downloading (100%)
[2019-07-04 06:36:31] OUT >   - Installing aws/aws-sdk-php (3.86.3): Loading from cache
```

```
[2019-07-04 06:38:06] OUT > [2019-07-03 14:37:52] error-log.ERROR: Uncaught Exception Error: "Call to undefined method Aws\DynamoDb\StandardSessionConnection::getDataAttribute()" at /var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/dynamodb/code/SessionHandler.php line 28 {"exception":"[object] (Error(code: 0): Call to undefined method Aws\\DynamoDb\\StandardSessionConnection::getDataAttribute() at /var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/dynamodb/code/SessionHandler.php:28)"} []
[2019-07-04 06:38:06] OUT > [2019-07-03 14:37:52] error-log.ALERT: Fatal Error (E_ERROR): Uncaught Error: Call to undefined method Aws\DynamoDb\StandardSessionConnection::getDataAttribute() in /var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/dynamodb/code/SessionHandler.php:28 Stack trace: #0 /var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/dynamodb/code/Model/DynamoDbSession.php(88): SilverStripe\DynamoDb\SessionHandler::fromClient(Object(SilverStripe\DynamoDb\DynamoDbClient), Array) #1 /var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/dynamodb/code/Model/DynamoDbSession.php(73): SilverStripe\DynamoDb\Model\DynamoDbSession->__construct(Array, '<REDACTED>') #2 /var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/dynamodb/_config.php(5): SilverStripe\DynamoDb\Model\DynamoDbSession::get() #3 /var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/framework/src/Core/Manifest/Module.php(289): require_once('/var/www/mysite.. {"code":1,"message":"Uncaught Error: Call to undefined method Aws\\DynamoDb\\StandardSessionConnection::getDataAttribute() in /var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/dynamodb/code/SessionHandler.php:28\nStack trace:\n#0 /var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/dynamodb/code/Model/DynamoDbSession.php(88): SilverStripe\\DynamoDb\\SessionHandler::fromClient(Object(SilverStripe\\DynamoDb\\DynamoDbClient), Array)\n#1 /var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/dynamodb/code/Model/DynamoDbSession.php(73): SilverStripe\\DynamoDb\\Model\\DynamoDbSession->__construct(Array, '<REDACTED>')\n#2 /var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/dynamodb/_config.php(5): SilverStripe\\DynamoDb\\Model\\DynamoDbSession::get()\n#3 /var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/framework/src/Core/Manifest/Module.php(289): require_once('/var/www/mysite..","file":"/var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/dynamodb/code/SessionHandler.php","line":28,"trace":null} []
[2019-07-04 06:38:06] OUT >   1: ERROR [Emergency]: Uncaught Error: Call to undefined method Aws\DynamoDb\StandardSessionConnection::getDataAttribute()
[2019-07-04 06:38:06] OUT >   2: IN GET dev/build
[2019-07-04 06:38:06] OUT >   3: Line 28 in /var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/dynamodb/code/SessionHandler.php
[2019-07-04 06:38:06] OUT >
[2019-07-04 06:38:06] OUT >   4: Source
[2019-07-04 06:38:06] OUT >   5: ======
[2019-07-04 06:38:06] OUT >   6:   19:  {
[2019-07-04 06:38:06] OUT >   7:   20:      /**
[2019-07-04 06:38:06] OUT >   8:   21:       * @var SessionConnectionInterface
[2019-07-04 06:38:06] OUT >   9:   22:       */
[2019-07-04 06:38:06] OUT >  10:   23:      private $connection;
[2019-07-04 06:38:06] OUT >  11:   24:
[2019-07-04 06:38:06] OUT >  12:   25:      public static function fromClient(\Aws\DynamoDb\DynamoDbClient $client, array $config = [])
[2019-07-04 06:38:06] OUT >  13:   26:      {
[2019-07-04 06:38:06] OUT >  14:   27:          $handler = parent::fromClient($client, $config);
[2019-07-04 06:38:06] OUT >  15: * 28:          $client->setSessionTableDataAttribute($handler->connection->getDataAttribute());
[2019-07-04 06:38:06] OUT >  16:   29:
[2019-07-04 06:38:06] OUT >  17:   30:          return $handler;
[2019-07-04 06:38:06] OUT >  18:   31:      }
[2019-07-04 06:38:06] OUT >  19:   32:
[2019-07-04 06:38:06] OUT >  20:   33:      public function __construct(SessionConnectionInterface $connection)
[2019-07-04 06:38:06] OUT >  21:   34:      {
[2019-07-04 06:38:06] OUT >
[2019-07-04 06:38:06] OUT >  22: Trace
[2019-07-04 06:38:06] OUT >  23: =====
[2019-07-04 06:38:06] OUT >  24: SilverStripe\DynamoDb\SessionHandler::fromClient(SilverStripe\DynamoDb\DynamoDbClient, Array)
[2019-07-04 06:38:06] OUT >  25: DynamoDbSession.php:88
[2019-07-04 06:38:06] OUT >
[2019-07-04 06:38:06] OUT >  26: SilverStripe\DynamoDb\Model\DynamoDbSession->__construct(Array, <REDACTED>)
[2019-07-04 06:38:06] OUT >  27: DynamoDbSession.php:73
[2019-07-04 06:38:06] OUT >
[2019-07-04 06:38:06] OUT >  28: SilverStripe\DynamoDb\Model\DynamoDbSession::get()
[2019-07-04 06:38:06] OUT >  29: _config.php:5
[2019-07-04 06:38:06] OUT >
[2019-07-04 06:38:06] OUT >  30: require_once(/var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/dynamodb/_config.php)
[2019-07-04 06:38:06] OUT >  31: Module.php:289
[2019-07-04 06:38:06] OUT >
[2019-07-04 06:38:06] OUT >  32: SilverStripe\Core\Manifest\requireFile(/var/www/mysite/releases/ce96b3372d089b2d4a7a5d706d40d633a76ad405/vendor/silverstripe/dynamodb/_config.php)
[2019-07-04 06:38:06] OUT >  33: Module.php:187
[2019-07-04 06:38:07] OUT >
[2019-07-04 06:38:07] OUT >  34: SilverStripe\Core\Manifest\Module->activate()
[2019-07-04 06:38:07] OUT >  35: ModuleManifest.php:153
[2019-07-04 06:38:07] OUT >
[2019-07-04 06:38:07] OUT >  36: SilverStripe\Core\Manifest\ModuleManifest->activateConfig()
[2019-07-04 06:38:07] OUT >  37: CoreKernel.php:213
[2019-07-04 06:38:07] OUT >
[2019-07-04 06:38:07] OUT >  38: SilverStripe\Core\CoreKernel->bootConfigs()
[2019-07-04 06:38:07] OUT >  39: CoreKernel.php:197
[2019-07-04 06:38:07] OUT >
[2019-07-04 06:38:07] OUT >  40: SilverStripe\Core\CoreKernel->boot(1)
[2019-07-04 06:38:07] OUT >  41: HTTPApplication.php:135
[2019-07-04 06:38:07] OUT >
[2019-07-04 06:38:07] OUT >  42: SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)
[2019-07-04 06:38:07] OUT >  43: HTTPMiddlewareAware.php:65
[2019-07-04 06:38:07] OUT >
[2019-07-04 06:38:07] OUT >  44: SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
[2019-07-04 06:38:07] OUT >  45: HTTPApplication.php:137
[2019-07-04 06:38:07] OUT >
[2019-07-04 06:38:07] OUT >  46: SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, 1)
[2019-07-04 06:38:07] OUT >  47: HTTPApplication.php:118
[2019-07-04 06:38:07] OUT >
[2019-07-04 06:38:07] OUT >  48: SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest)
[2019-07-04 06:38:07] OUT >  49: cli-script.php:22
```

**Comment by indygriffiths** [comment]
Closing as issue was related to the `aws/aws-sdk-php` which required an update
